# Generated by Django 4.2.4 on 2023-10-09 16:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Administrator",
        ),
    ]
