openapi: 3.0.3
info:
  title: Your Project API
  version: 1.0.0
  description: Your project description
paths:
  /api/v1/research/invites/:
    get:
      operationId: invites_list
      parameters:
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      tags:
      - invites
      security:
      - cookieAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedInviteList'
          description: ''
    post:
      operationId: invites_create
      tags:
      - invites
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Invite'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Invite'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Invite'
        required: true
      security:
      - cookieAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Invite'
          description: ''
  /api/v1/research/invites/{id}/:
    get:
      operationId: invites_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - invites
      security:
      - cookieAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Invite'
          description: ''
    put:
      operationId: invites_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - invites
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Invite'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Invite'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Invite'
        required: true
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Invite'
          description: ''
    patch:
      operationId: invites_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - invites
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedInvite'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedInvite'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedInvite'
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Invite'
          description: ''
    delete:
      operationId: invites_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - invites
      security:
      - cookieAuth: []
      responses:
        '204':
          description: No response body
  /api/v1/research/projects/:
    get:
      operationId: projects_list
      parameters:
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      tags:
      - projects
      security:
      - cookieAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedThesisProjectList'
          description: ''
    post:
      operationId: projects_create
      tags:
      - projects
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ThesisProject'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/ThesisProject'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/ThesisProject'
        required: true
      security:
      - cookieAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThesisProject'
          description: ''
  /api/v1/research/projects/{id}/:
    get:
      operationId: projects_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - projects
      security:
      - cookieAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThesisProject'
          description: ''
    put:
      operationId: projects_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - projects
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ThesisProject'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/ThesisProject'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/ThesisProject'
        required: true
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThesisProject'
          description: ''
    patch:
      operationId: projects_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - projects
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedThesisProject'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedThesisProject'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedThesisProject'
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThesisProject'
          description: ''
    delete:
      operationId: projects_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - projects
      security:
      - cookieAuth: []
      responses:
        '204':
          description: No response body
components:
  schemas:
    Invite:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        type:
          $ref: '#/components/schemas/TypeEnum'
        sender:
          type: integer
        sender_name:
          type: string
          readOnly: true
        receiver:
          type: integer
        receiver_name:
          type: string
          readOnly: true
        created_at:
          type: string
          format: date-time
          readOnly: true
        accepted:
          type: boolean
      required:
      - created_at
      - id
      - receiver
      - receiver_name
      - sender
      - sender_name
    PaginatedInviteList:
      type: object
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=4
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=2
        results:
          type: array
          items:
            $ref: '#/components/schemas/Invite'
    PaginatedThesisProjectList:
      type: object
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=4
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=2
        results:
          type: array
          items:
            $ref: '#/components/schemas/ThesisProject'
    PatchedInvite:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        type:
          $ref: '#/components/schemas/TypeEnum'
        sender:
          type: integer
        sender_name:
          type: string
          readOnly: true
        receiver:
          type: integer
        receiver_name:
          type: string
          readOnly: true
        created_at:
          type: string
          format: date-time
          readOnly: true
        accepted:
          type: boolean
    PatchedThesisProject:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        title:
          type: string
          maxLength: 255
        description:
          type: string
          nullable: true
        authors:
          type: string
          readOnly: true
        advisor:
          type: integer
        approved:
          type: boolean
        approved_at:
          type: string
          format: date
          nullable: true
        committee:
          type: string
          nullable: true
          maxLength: 100
        defense_date:
          type: string
          format: date
          nullable: true
        invite:
          type: integer
    ThesisProject:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        title:
          type: string
          maxLength: 255
        description:
          type: string
          nullable: true
        authors:
          type: string
          readOnly: true
        advisor:
          type: integer
        approved:
          type: boolean
        approved_at:
          type: string
          format: date
          nullable: true
        committee:
          type: string
          nullable: true
          maxLength: 100
        defense_date:
          type: string
          format: date
          nullable: true
        invite:
          type: integer
      required:
      - advisor
      - authors
      - id
      - invite
      - title
    TypeEnum:
      enum:
      - 1
      - 2
      type: integer
      description: |-
        * `1` - TCC I
        * `2` - TCC II
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
