# Generated by Django 4.2.4 on 2023-09-13 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hashid_field.field
import research.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("acronym", models.CharField(max_length=4)),
            ],
            options={
                "verbose_name": "Curso",
            },
        ),
        migrations.CreateModel(
            name="Invite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "TCC I"), (2, "TCC II")], default=1
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("accepted", models.BooleanField(default=False)),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_invites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_invites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Convite",
            },
        ),
        migrations.CreateModel(
            name="ThesisProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("approved", models.BooleanField(default=False)),
                ("approved_at", models.DateField(blank=True, null=True)),
                (
                    "type",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "TCC I"), (2, "TCC II")], default=1
                    ),
                ),
                ("committee", models.CharField(blank=True, max_length=100, null=True)),
                ("defense_date", models.DateField(blank=True, null=True)),
                ("file", models.FileField(blank=True, null=True, upload_to="")),
                (
                    "advisor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="research_advisor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "authors",
                    models.ManyToManyField(
                        related_name="research_authors", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "invite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="research.invite",
                    ),
                ),
                (
                    "responsible",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Professor Responsável",
                    ),
                ),
            ],
            options={
                "verbose_name": "Projeto de TCC",
                "verbose_name_plural": "Projetos de TCC",
            },
        ),
        migrations.CreateModel(
            name="FileVersion",
            fields=[
                (
                    "hash_id",
                    hashid_field.field.HashidAutoField(
                        alphabet="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890",
                        min_length=7,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "version_number",
                    models.PositiveIntegerField(blank=True, editable=False, null=True),
                ),
                ("comments", models.TextField(blank=True, null=True)),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=research.models.file_upload_path,
                        validators=[research.models.validate_pdf_extension],
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file_versions",
                        to="research.thesisproject",
                    ),
                ),
            ],
        ),
    ]
