# Generated by Django 4.2.4 on 2023-11-04 18:51

from django.db import migrations, models
import utilities.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UsefulFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Título do recurso a ser compartilhado",
                        max_length=255,
                        verbose_name="Título",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="Arquivo a ser compartilhado",
                        null=True,
                        upload_to=utilities.models.file_upload_path,
                        verbose_name="Arquivo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Arquivo Útil",
                "verbose_name_plural": "Arquivos Úteis",
            },
        ),
        migrations.CreateModel(
            name="UsefulLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Título do recurso a ser compartilhado",
                        max_length=255,
                        verbose_name="Título",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="URL do recurso a ser compartilhado",
                        verbose_name="URL",
                    ),
                ),
            ],
            options={
                "verbose_name": "Links Útil",
                "verbose_name_plural": "Links Úteis",
            },
        ),
    ]
